# Everything is this config supports color code using the '&' symbol with the corresponding number after it.
# Example: &4Example of &bcolor &c code
#DO NOT CHANGE THE IDENTIFIERS, THIS WILL BREAK THE PLUGIN!!! PLEASE CHANGE JUST THE VALUES!

LANG:
  NO_PERMISSION: '&4You do not have the required permissions to execute this command!'
  SENDER_NOT_PLAYER: '&4You cannot execute this command from the terminal'

OPTIONS:
  PREFIX:
    USE_PREFIX: true
    PREFIX_TEXT: '&7[&b&lIIR&r&7] '


GUI:
  PLACE_ITEMS_GUI:
    TITLE: "&cPlace your banned items here: "
    SIZE: 9
    ITEMS:
      PAPER:
        NAME: "&7Next Step"
        LORE:
          - "Click me"
          - "to go to"
          - "the next step!"
  REPLACEMENT_ITEMS_GUI:
    TITLE: "&cPlace your replacement items here: "
    ITEMS:
      PAPER:
        NAME: "&aSubmit"
        LORE:
          - "Click me"
          - "to Submit!"
