name: IllegalItemReplacer
main: me.Xaxis.replace.IIR
version: 1.0
commands:
  replaceItem:
    description: Replace items.
    aliases:
      - ri
    permission: IllegalItemReplacer.replaceItems
  setPanicChestLocation:
    description: set the panic chest location in case for some reason something goes wrong...
    aliases:
      - spcl
    permission: IllegalItemReplacer.setPanicChestLocation